<a href="https://colab.research.google.com/github/shinieaggarwal72/Principal-Component-Analysis/blob/main/PCA.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd

In [2]:
import csv

with open('/content/banknote_dataset.txt', 'r') as in_file:
    stripped = (line.strip() for line in in_file)
    lines = (line.split(",") for line in stripped if line)
    with open('data.csv', 'w') as out_file:
        writer = csv.writer(out_file)
        writer.writerow(('variance', 'skewness', 'kurtosis', 'entropy', 'class'))
        writer.writerows(lines)

In [3]:
df = pd.read_csv('/content/data.csv')

In [4]:
print(df.head)

<bound method NDFrame.head of       variance  skewness  kurtosis  entropy  class
0      3.62160   8.66610   -2.8073 -0.44699      0
1      4.54590   8.16740   -2.4586 -1.46210      0
2      3.86600  -2.63830    1.9242  0.10645      0
3      3.45660   9.52280   -4.0112 -3.59440      0
4      0.32924  -4.45520    4.5718 -0.98880      0
...        ...       ...       ...      ...    ...
1367   0.40614   1.34920   -1.4501 -0.55949      1
1368  -1.38870  -4.87730    6.4774  0.34179      1
1369  -3.75030 -13.45860   17.5932 -2.77710      1
1370  -3.56370  -8.38270   12.3930 -1.28230      1
1371  -2.54190  -0.65804    2.6842  1.19520      1

[1372 rows x 5 columns]>


In [5]:
w = df['variance']

In [6]:
print(w)

0       3.62160
1       4.54590
2       3.86600
3       3.45660
4       0.32924
         ...   
1367    0.40614
1368   -1.38870
1369   -3.75030
1370   -3.56370
1371   -2.54190
Name: variance, Length: 1372, dtype: float64


In [7]:
w_mean = np.mean(w)
print(w_mean)

0.4337352570699707


In [8]:
x = df['skewness']
x_mean = np.mean(x)
print(x_mean)

1.9223531206393585


In [9]:
y = df['kurtosis']
y_mean = np.mean(y)
print(y_mean)

1.3976271172667638


In [10]:
z = df['entropy']
z_mean = np.mean(z)
print(z_mean)

-1.1916565200437317


In [45]:
res = df['class']
res_mean = np.mean(res)
print(res_mean)

0.4446064139941691


In [11]:
w = w - w_mean
x = x - x_mean
y = y - y_mean
z = z - z_mean

In [12]:
cov_ww = 0
for i in range(0,df.shape[0]):
  cov_ww += (w[i]-w_mean)*(w[i]-w_mean)/df.shape[0]

print(cov_ww)

8.263535235460859


In [13]:
cov_wx = 0
for i in range(0,df.shape[0]):
  cov_wx += (w[i]-w_mean)*(x[i]-x_mean)/df.shape[0]

print(cov_wx)

5.235664489039956


In [14]:
cov_wy = 0
for i in range(0,df.shape[0]):
  cov_wy += (w[i]-w_mean)*(y[i]-y_mean)/df.shape[0]

print(cov_wy)

-4.056721992337697


In [15]:
cov_wz = 0
for i in range(0,df.shape[0]):
  cov_wz += (w[i]-w_mean)*(z[i]-z_mean)/df.shape[0]

print(cov_wz)

1.1352694663509812


In [16]:
cov_xw = cov_wx

In [17]:
cov_xx = 0
for i in range(0,df.shape[0]):
  cov_xx += (x[i]-x_mean)*(x[i]-x_mean)/df.shape[0]

print(cov_xx)

38.11604499772443


In [18]:
cov_xy = 0
for i in range(0,df.shape[0]):
  cov_xy += (x[i]-x_mean)*(y[i]-y_mean)/df.shape[0]

print(cov_xy)

-17.20387813130577


In [19]:
cov_xz = 0
for i in range(0,df.shape[0]):
  cov_xz += (x[i]-x_mean)*(z[i]-z_mean)/df.shape[0]

print(cov_xz)

-8.776087285084108


In [20]:
cov_yw = cov_wy

In [21]:
cov_yx = cov_xy

In [22]:
cov_yy = 0
for i in range(0,df.shape[0]):
  cov_yy += (y[i]-y_mean)*(y[i]-y_mean)/df.shape[0]

print(cov_yy)

20.516181316006065


In [23]:
cov_yz = 0
for i in range(0,df.shape[0]):
  cov_yz += (y[i]-y_mean)*(z[i]-z_mean)/df.shape[0]

print(cov_yz)

1.2196454189754953


In [24]:
cov_zw = cov_wz
cov_zx = cov_xz
cov_zy = cov_yz

In [25]:

cov_zz = 0
for i in range(0,df.shape[0]):
  cov_zz += (z[i]-z_mean)*(z[i]-z_mean)/df.shape[0]

print(cov_zz)

5.831084077217092


In [26]:
cov_matrix = [[cov_ww,cov_wx,cov_wy,cov_wz],[cov_xw,cov_xx,cov_xy,cov_xz],[cov_yw,cov_yx,cov_yy,cov_yz],[cov_zw,cov_zx,cov_zy,cov_zz]]
print(cov_matrix)

[[8.263535235460859, 5.235664489039956, -4.056721992337697, 1.1352694663509812], [5.235664489039956, 38.11604499772443, -17.20387813130577, -8.776087285084108], [-4.056721992337697, -17.20387813130577, 20.516181316006065, 1.2196454189754953], [1.1352694663509812, -8.776087285084108, 1.2196454189754953, 5.831084077217092]]


In [27]:
iden_mat = np.eye(4)
print(iden_mat)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [28]:
eig_val, eig_vect = np.linalg.eig(cov_matrix)

In [29]:
print(eig_val)

[51.05699904 12.2824613   2.0885067   7.29887859]


In [30]:
sorted_indices = np.argsort(eig_val)[::-1]
sorted_eigval = eig_val[sorted_indices]
sorted_eigvect = eig_vect[ sorted_indices, :]

In [31]:
print(sorted_eigvect)

[[ 0.14509139  0.34384286 -0.32363032  0.8694734 ]
 [ 0.83746814 -0.39270497  0.3508219   0.14612981]
 [-0.17229599  0.45877685  0.8557637   0.1658505 ]
 [-0.49790531 -0.71908185  0.19963944  0.4417643 ]]


In [32]:
sum_eigval = np.sum(eig_val)
#print(sum_eigval)
per_var1 = (sorted_eigval[0]/sum_eigval)*100
per_var2 = (sorted_eigval[1]/sum_eigval)*100
per_var3 = (sorted_eigval[2]/sum_eigval)*100
per_var4 = (sorted_eigval[3]/sum_eigval)*100
print(per_var1)
print(per_var2)
print(per_var3)
print(per_var4)

70.20378595717538
16.888483462440355
10.036017001461412
2.871713578922851


usually, we take the threshold value of 95%

In [57]:
#taking first three eigen vectors
pc1 = sorted_eigvect[0,:]
pc2 = sorted_eigvect[1,:]
pc3 = sorted_eigvect[2,:]
pc = []
pc.append(pc1)
pc.append(pc2)
pc.append(pc3)
pc = np.array(pc)
print(pc)


[[ 0.14509139  0.34384286 -0.32363032  0.8694734 ]
 [ 0.83746814 -0.39270497  0.3508219   0.14612981]
 [-0.17229599  0.45877685  0.8557637   0.1658505 ]]


In [50]:
df['variance'] = df['variance'] - df['variance'].mean()
df['skewness'] = df['skewness'] - df['skewness'].mean()
df['kurtosis'] = df['kurtosis'] - df['kurtosis'].mean()
df['entropy'] = df['entropy'] - df['entropy'].mean()

In [53]:
df_x = df.drop(['class'], axis=1)

df_x = np.array(df_x)


In [59]:
New_dataset = np.dot(pc, df_x.transpose())

In [60]:
print(New_dataset)

[[  4.78963057   3.75680307  -0.1119018  ... -12.51557771  -7.76056047
    0.33994545]
 [ -1.34493027  -0.40102274   5.03982886 ...   7.9862615    4.54329273
   -0.6785177 ]
 [ -0.93030205  -1.18829894  -2.01777392 ...   7.2611041    5.35542999
    0.82572911]]
